version: "3.8"
services:
  db:
    container_name: billz_postgres
    image: "postgres:12.11"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=billz_packages
    ports:
      - "5432:5432"

  # https://stackoverflow.com/questions/46627979/what-is-the-default-user-and-password-for-elasticsearch
  # https://www.elastic.co/guide/en/x-pack/current/security-getting-started.html
  elasticsearch:
    image: elasticsearch:7.13.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - http.port=9200
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    # network_mode: host
  # http://localhost:5601/app/dev_tools#/console
  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:7.13.1
    #    ports:
    #      - 5601:5601
    network_mode: host
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://127.0.0.1:9200
      - ELASTICSEARCH_USERNAME=kibana
      - ELASTICSEARCH_PASSWORD=kibana

  #  zookeeper:
  #    image: 'bitnami/zookeeper:latest'
  #    environment:
  #      - ALLOW_ANONYMOUS_LOGIN=yes
  #    network_mode: host
  #  kafka:
  #    image: 'bitnami/kafka:2.8'
  #    network_mode: host
  #    environment:
  #      - ALLOW_PLAINTEXT_LISTENER=yes
  #
  #  kafdrop:
  #    image: obsidiandynamics/kafdrop
  #    restart: "no"
  #    network_mode: host
  ##    ports:
  ##      - "9000:9000"
  #    environment:
  #      KAFKA_BROKERCONNECT: "127.0.0.1:9092"
  ##      KAFKA_BROKERCONNECT: "kafka:9092"
  #      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
  #    depends_on:
  #      - "kafka"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  # http://localhost:9000/
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9999:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - "kafka"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - ./storage/minio:/data
    environment:
      MINIO_ACCESS_KEY: 2wjyybzuy3g4ednkmpgmhczzdvfbk87d
      MINIO_SECRET_KEY: tgetjnczdxx9engvkthsy8cy8p25yqmz
    command: server /data

  cache:
    image: docker.io/bitnami/redis:7.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PASSWORD=""
      - REDIS_DATABASE=0
    ports:
      - "6379:6379"

  jaeger:
    image: jaegertracing/all-in-one:1.63.0
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686" # web
      - "4317:4317" # grpc
      - "4318:4318" # http

  prometheus:
    image: prom/prometheus:v3.14.0
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana-oss:11.3.0
    ports:
      - "3000:3000"
