package logger

type LogLevel string

const (
	// LevelDebug ...
	LevelDebug LogLevel = "debug"
	// LevelInfo ...
	LevelInfo LogLevel = "info"
	// LevelWarn ...
	LevelWarn LogLevel = "warn"
	// LevelError ...
	LevelError LogLevel = "error"
	// LevelPanic ...
	LevelPanic LogLevel = "panic"
	// LevelFatal ...
	LevelFatal LogLevel = "fatal"
)
