// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/billz-2/packages/pkg/userclient (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -destination pkg/userclient/mock/mock_client.go -package mock_userclient github.com/billz-2/packages/pkg/userclient Client
//

// Package mock_userclient is a generated GoMock package.
package mock_userclient

import (
	context "context"
	reflect "reflect"

	userclient "github.com/billz-2/packages/pkg/userclient"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetUserByID mocks base method.
func (m *MockClient) GetUserByID(ctx context.Context, userID string) (*userclient.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, userID)
	ret0, _ := ret[0].(*userclient.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockClientMockRecorder) GetUserByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockClient)(nil).GetUserByID), ctx, userID)
}

// GetUsersByIDs mocks base method.
func (m *MockClient) GetUsersByIDs(ctx context.Context, userIDs []string) (map[string]*userclient.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersByIDs", ctx, userIDs)
	ret0, _ := ret[0].(map[string]*userclient.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersByIDs indicates an expected call of GetUsersByIDs.
func (mr *MockClientMockRecorder) GetUsersByIDs(ctx, userIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersByIDs", reflect.TypeOf((*MockClient)(nil).GetUsersByIDs), ctx, userIDs)
}
