// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/billz-2/packages/pkg/amoCRM (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -destination pkg/amoCRM/mock/client.go -package mock_amocrm github.com/billz-2/packages/pkg/amoCRM Client
//

// Package mock_amocrm is a generated GoMock package.
package mock_amocrm

import (
	reflect "reflect"

	amocrm "github.com/billz-2/packages/pkg/amoCRM"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Leads mocks base method.
func (m *MockClient) Leads() amocrm.Leads {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Leads")
	ret0, _ := ret[0].(amocrm.Leads)
	return ret0
}

// Leads indicates an expected call of Leads.
func (mr *MockClientMockRecorder) Leads() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Leads", reflect.TypeOf((*MockClient)(nil).Leads))
}
