// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/billz-2/packages/pkg/amoCRM (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -destination client.go -package mock_amocrm github.com/billz-2/packages/pkg/amoCRM Client
//

// Package mock_amocrm is a generated GoMock package.
package mock_amocrm

import (
	context "context"
	reflect "reflect"

	amocrm "github.com/billz-2/packages/pkg/amoCRM"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Leads mocks base method.
func (m *MockClient) Leads() amocrm.Leads {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Leads")
	ret0, _ := ret[0].(amocrm.Leads)
	return ret0
}

// Leads indicates an expected call of Leads.
func (mr *MockClientMockRecorder) Leads() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Leads", reflect.TypeOf((*MockClient)(nil).Leads))
}

// SetDomain mocks base method.
func (m *MockClient) SetDomain(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDomain", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDomain indicates an expected call of SetDomain.
func (mr *MockClientMockRecorder) SetDomain(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDomain", reflect.TypeOf((*MockClient)(nil).SetDomain), arg0, arg1)
}

// SetToken mocks base method.
func (m *MockClient) SetToken(arg0 context.Context, arg1 amocrm.Token) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetToken", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetToken indicates an expected call of SetToken.
func (mr *MockClientMockRecorder) SetToken(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetToken", reflect.TypeOf((*MockClient)(nil).SetToken), arg0, arg1)
}

// TokenByCode mocks base method.
func (m *MockClient) TokenByCode(arg0 context.Context, arg1 string) (amocrm.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TokenByCode", arg0, arg1)
	ret0, _ := ret[0].(amocrm.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TokenByCode indicates an expected call of TokenByCode.
func (mr *MockClientMockRecorder) TokenByCode(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TokenByCode", reflect.TypeOf((*MockClient)(nil).TokenByCode), arg0, arg1)
}
