// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/billz-2/packages/pkg/amoCRM (interfaces: Leads)
//
// Generated by this command:
//
//	mockgen -destination leads.go -package mock_amocrm github.com/billz-2/packages/pkg/amoCRM Leads
//

// Package mock_amocrm is a generated GoMock package.
package mock_amocrm

import (
	context "context"
	reflect "reflect"

	amocrm "github.com/billz-2/packages/pkg/amoCRM"
	gomock "go.uber.org/mock/gomock"
)

// MockLeads is a mock of Leads interface.
type MockLeads struct {
	ctrl     *gomock.Controller
	recorder *MockLeadsMockRecorder
}

// MockLeadsMockRecorder is the mock recorder for MockLeads.
type MockLeadsMockRecorder struct {
	mock *MockLeads
}

// NewMockLeads creates a new mock instance.
func NewMockLeads(ctrl *gomock.Controller) *MockLeads {
	mock := &MockLeads{ctrl: ctrl}
	mock.recorder = &MockLeadsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLeads) EXPECT() *MockLeadsMockRecorder {
	return m.recorder
}

// BatchUpdate mocks base method.
func (m *MockLeads) BatchUpdate(arg0 context.Context, arg1 []*amocrm.LeadUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdate", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpdate indicates an expected call of BatchUpdate.
func (mr *MockLeadsMockRecorder) BatchUpdate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdate", reflect.TypeOf((*MockLeads)(nil).BatchUpdate), arg0, arg1)
}

// Update mocks base method.
func (m *MockLeads) Update(arg0 context.Context, arg1 *amocrm.LeadUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockLeadsMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockLeads)(nil).Update), arg0, arg1)
}
