// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/billz-2/packages/pkg/user_event_log (interfaces: Kafka)

// Package mock_usereventlog is a generated GoMock package.
package mock_usereventlog

import (
	reflect "reflect"

	cloudevents "github.com/cloudevents/sdk-go/v2"
	gomock "github.com/golang/mock/gomock"
)

// MockKafka is a mock of Kafka interface.
type MockKafka struct {
	ctrl     *gomock.Controller
	recorder *MockKafkaMockRecorder
}

// MockKafkaMockRecorder is the mock recorder for MockKafka.
type MockKafkaMockRecorder struct {
	mock *MockKafka
}

// NewMockKafka creates a new mock instance.
func NewMockKafka(ctrl *gomock.Controller) *MockKafka {
	mock := &MockKafka{ctrl: ctrl}
	mock.recorder = &MockKafkaMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKafka) EXPECT() *MockKafkaMockRecorder {
	return m.recorder
}

// Push mocks base method.
func (m *MockKafka) Push(topic string, e cloudevents.Event, partitionKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Push", topic, e, partitionKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// Push indicates an expected call of Push.
func (mr *MockKafkaMockRecorder) Push(topic, e, partitionKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Push", reflect.TypeOf((*MockKafka)(nil).Push), topic, e, partitionKey)
}

